# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: WildFly Plugin Tools Integration Tests

on:
  push:
    branches:
      - '**'
    paths:
      - '.github/workflows/integration-tests.yml'
      - '**/pom.xml'
      - 'src/main/**'
      - '!src/test/**'
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/workflows/integration-tests.yml'
      - '**/pom.xml'
      - 'src/**'
      - '!src/test/**'
  schedule:
    - cron: '0 0 * * *' # Every day at 00:00 UTC

# Only run the latest job
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  MVN_CMD: 'mvn -V -B'

jobs:

  arquillian-test:
    name: WildFly Arquillian Integration Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v6
        with:
          path: wildfly-plugin-tools
      - name: Set up JDKs
        uses: actions/setup-java@v5
        with:
          java-version: |
            25
          distribution: 'temurin'
          architecture: x64
          cache: 'maven'

      - name: Install SNAPSHOT
        run: |
          cd wildfly-plugin-tools
          ${{ env.MVN_CMD }} install -DskipTests
      - name: Check out WildFly Arquillian
        uses: actions/checkout@v6
        with:
          repository: wildfly/wildfly-arquillian
          path: wildfly-arquillian
        # The first run needs to use install as the SNAPSHOT dependencies are required for testing
      - name: Test WildFly Arquillian Java 25
        run: |
          cd wildfly-arquillian
          ${{ env.MVN_CMD }} versions:use-latest-snapshots -DallowSnapshots -Dincludes=org.wildfly.plugins:wildfly-plugin-tools versions:update-properties
          git diff
          ${{ env.MVN_CMD }} clean install
      - name: Upload test logs for failed run
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: wildfly-arquillian-reports
          path: |
            **/logs/
            **/*.log
            **/failsafe-reports/
            **/surefire-reports/

  maven-plugin-test:
    name: WildFly Maven Plugin Integration Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v6
        with:
          path: wildfly-plugin-tools
      - name: Set up JDKs
        uses: actions/setup-java@v5
        with:
          java-version: |
            25
          distribution: 'temurin'
          architecture: x64
          cache: 'maven'

      - name: Install SNAPSHOT
        run: |
          cd wildfly-plugin-tools
          ${{ env.MVN_CMD }} install -DskipTests
      - name: Check out WildFly Maven Plugin
        uses: actions/checkout@v6
        with:
          repository: wildfly/wildfly-maven-plugin
          path: wildfly-maven-plugin
        # The first run needs to use install as the SNAPSHOT dependencies are required for testing
      - name: Test the WildFly Maven Plugin Java 25
        run: |
          cd wildfly-maven-plugin
          ${{ env.MVN_CMD }} versions:use-latest-snapshots -DallowSnapshots -Dincludes=org.wildfly.plugins:wildfly-plugin-tools versions:update-properties
          git diff
          ${{ env.MVN_CMD }} clean install
      - name: Upload test logs for failed run
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: wildfly-maven-plugin-reports
          path: |
            **/logs/
            **/*.log
            **/failsafe-reports/
            **/surefire-reports/

  wildfly-glow-test:
    name: WildFly Glow Integration Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v6
        with:
          path: wildfly-plugin-tools
      - name: Set up JDKs
        uses: actions/setup-java@v5
        with:
          java-version: |
            25
          distribution: 'temurin'
          architecture: x64
          cache: 'maven'

      - name: Install SNAPSHOT
        run: |
          cd wildfly-plugin-tools
          ${{ env.MVN_CMD }} install -DskipTests
      - name: Check out WildFly Glow
        uses: actions/checkout@v6
        with:
          repository: wildfly/wildfly-glow
          path: wildfly-glow
      - name: Test the WildFly Glow Java 25
        # The first run needs to use install as the SNAPSHOT dependencies are required for testing
        run: |
          cd wildfly-glow
          ${{ env.MVN_CMD }} versions:use-latest-snapshots -DallowSnapshots -Dincludes=org.wildfly.plugins:wildfly-plugin-tools versions:update-properties
          git diff
          ${{ env.MVN_CMD }} clean install
      - name: Upload test logs for failed run
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: wildfly-glow-reports
          path: |
            **/logs/
            **/*.log
            **/failsafe-reports/
            **/surefire-reports/
